### PR TITLE
Bringing UniGrid in line (cherry-picked)

### PR DESCRIPTION
**Pull request by Crown421**
* Redoing #27 without unrelated commits

This is my attempt to make UniGrid return something that looks like a Vector, while being as efficient as I can make it.
I spent much time looking into "Lazy" implementations, but the best I could find was "Iterators.product", which returns Tuples, which don't work with some of the ApproximateGPs.jl stuff that I played with.

I had to change some eltype(...) == Vector(...) into eltype(...) <: AbstractVector to make the tests work with ColVecs output.

This is not final just yet, as there is some more polish to do. Either in this PR or in another one, I think it would be good to streamline the output types. I personally like what can be seen in KmeansAlg, which returns a Vector{<:Real} for scalar inputs x and a ColVecs otherwise (i.e multidim inputs), and I think that perhaps all methods could do that.

### CODE REVIEW

**Comment by Crown421** [comment]
> I had more something like this in mind:
> 
> ```julia
> struct UniformGrid{T,Tl} <: AbstractVector{T}
>   grids::Tl # Collection of LinRange
> end
> 
> Base.length(grid::UniformGrid) = product(length, grid.grids)
> 
> getindex(grid::UniformGrid, i) = collect(getindex(Iterators.product(grid.grids), i))
> 
> ## Add more functions
> ```
> 
> And maybe try to use the specialization of the kernelkron matrix interface. This way, even for high-dimensional inputs we never fully allocate the matrix.
> 
> But maybe there is an already existing implementation somewhere, I will look into it.

copying

**Comment by theogf** [comment]
So the closest thing I found is :
```julia
using LazyGrids
struct UniformGrid{T,Tg,Tl} <: AbstractVector{T}
   linranges::Tl #  A vector of linranges
   grids::Tg # AbstractVector of lazy Array{T,D}
end
UniGrid(args::VarArgs{<:AbstractVector}) = UniGrid(collect(args), collect(ndgrid(args...)))
function update!(grid::UniGrid, args...)
  # Update grid.linranges in-place (it's a vector so we can)
  # Recompute the lazy instances of grid.grids
end
Base.getindex(grid::Unigrid, i) = getindex.(grid.grids, i)
Base.length(grid::Unigrid) = length(first(grid.grids))
```

I am not sure what the most efficient method is

**Comment by Crown421** [comment]
I can run some tests? In my experiments yesterday I found that many of the "lazy" implementations had substantially higher computation costs, but that might be worth it for really high-dim use cases. 

That said, I am not sure if it doesn't become a GP problem before one reaches the number of points where the memory for `Z` would be an issue?

**Comment by theogf** [comment]
> That said, I am not sure if it doesn't become a GP problem before one reaches the number of points where the memory for Z would be an issue?

The more general idea is to take advantage of it. For `D < 3` etc it can work for small `N` but then it will directly be intractable.
Generally one should use `UniGrid` with `kernelkronmatrix` but we still need to provide a standard interface for `kernelmatrix`

**Comment by Crown421** [comment]
Ah, that is right. I now also remember some Toeplitz stuff that one can get for the kernel matrix for some kernels on a uniform grid. 

That would make making a custom type worthwhile. I can give this a shot today.

**Comment by theogf** [comment]
I think the best shot would be to write a wrapper around `Iterators.product` while keeping the 1d grid to pass to kernelkronmat

**Comment by Crown421** [comment]
This is obsolete now (implemented #31 )

**Pull request closed without merging**
